#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5

bspc config border_width         0
bspc config window_gap          10
bspc config left_padding        -4
bspc config right_padding       -4
bspc config top_padding         -4

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# [AUTO START]
sxhkd &
setxkbmap latam &
picom --config $HOME/.config/picom/picom.conf.example &
nitrogen --restore &
dunst &
polybar --config=$HOME/.config/polybar/my-config.ini &
